refs #3 update/delete追加
sitateru/exam pull request #13
Opened 2019-09-29 10:06 UTC by hamapu

```
既存のIssueを更新するAPIを追加する
既存のIssueを削除するAPIを追加する
Issueの削除は論理削除とする
```

2019-09-30 10:56 UTC, tibaraki commented on config/routes.rb
> +  post 'issues/delete' => 'issues#delete'
RESTを前提とした場合、削除はHTTPのDELETEメソッド（POSTでなく）で実装されるのが一般的です。
また、UPDATEはPATCH/PUTメソッドで実装されるのが好ましいです。

参考：
https://railsguides.jp/routing.html#crud%E3%80%81%E5%8B%95%E8%A9%9E%E3%80%81%E3%82%A2%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3

2019-10-01 04:22 UTC, tibaraki commented on config/routes.rb
> +  delete 'issues/:id' => 'issues#delete'
```resources :issues```
で削除や更新のルーティングも定義されますので、この2行は冗長かもしれません

2019-10-01 04:22 UTC, tibaraki approved these changes

2019-10-01 20:29 UTC, tibaraki commented
@hamapu 

すみません、重大な点を見落としていました
現時点の実装だとdeleteが削除になっていません（findしかしていない）。論理削除になるように修正をお願いします

2019-10-01 20:30 UTC, tibaraki requested changes
削除実装が不十分なのでapproveを取り消しておきます

2019-10-02 14:42 UTC, hamapu commented
@tibaraki 
del_flgを1にしているのですが、もう一度ご確認いただけますか？「論理削除」の意味を取り違えていたら、その点に関してご返信ください

2019-10-03 01:00 UTC, tibaraki commented
@hamapu 
> del_flgを1にしているのですが、もう一度ご確認いただけますか？「論理削除」の意味を取り違えていたら、その点に関してご返信ください

あ、重ねて失礼しました。おっしゃるとおりですね。レビュー甘くすみません

2019-10-29 02:53 UTC, closed without merging